name: Blog post workflow
on:
  push:
  workflow_dispatch:
  schedule:
    # Runs every day at 9am UTC
    - cron: '0 09 * * *'
permissions:
  contents: write
  
jobs:
  pull_blog_rss:
    name: Update with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://jhuesser.ch/blog/rss
          count: 6 # default 5
      - name: Commit file changes
        run: |
            git config --global user.name 'rss-updater'
            git config --global user.email 'git-rss-updater@jhuesser.ch'
            git add .
            git diff --quiet --cached || git commit -m "Update RSS feed"    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}